POST http://127.0.0.1:3000/register
Content-Type: application/json

{
    "username": "taller",
    "password": "taller"
}

### LOGIN AN USER
POST http://127.0.0.1:3000/login
Content-Type: application/json

{
    "username": "taller",
    "password": "tallers"
}

