@baseURL=http://127.0.0.1:8443

POST {{baseURL}}/register
Content-Type: application/json

{
    "username": "taller",
    "password": "taller"
}

### LOGIN AN USER
POST {{baseURL}}/login
Content-Type: application/json

{
    "username": "taller",
    "password": "taller"
}
