#@baseURL=http://192.168.1.101:8443
@baseURL=http://127.0.0.1:8443

POST {{baseURL}}/register
Content-Type: application/json

{
    "username": "sigar",
    "password": "sigar"
}

### LOGIN AN USER
POST {{baseURL}}/login
Content-Type: application/json

{
  "password": "taller",
  "username": "taller"
}
