@baseURL=http://127.0.0.1:8443/lookup
#@baseURL=http://app.tecnoelectronics.com.ve:9052/lookup

### CREATE BRIGADE 
POST {{baseURL}}/brigade
Content-Type: application/json

{
  "name": "Directivos"
}

### GET BRIGADES 
GET {{baseURL}}/lookup/brigades

### Create state
POST {{baseURL}}/state
Content-Type: application/json

{
  "name": "Miranda"
}

### Create municipalty
POST {{baseURL}}/municipality
Content-Type: application/json

{
  "name": "Libertador",
  "state": 24
}

### Get charges
GET {{baseURL}}/charge

### Create an charge 
POST {{baseURL}}/charge
Content-Type: application/json

{
  "name": "Primer oficial"
}

### Create an hierarchy 
POST {{baseURL}}/hierarchy
Content-Type: application/json

{
  "name": "Jefe"
}

### Create an organism
POST {{baseURL}}/organism
Content-Type: application/json

{
  "name": "Jefe",
  "phone": "04120196456"
}

### Create an division 
POST {{baseURL}}/organism
Content-Type: application/json

{
  "name": "Jefe",
  "state": "Miranda"
}

### Create a brand
POST {{baseURL}}/brand
Content-Type: application/json

{
  "name": "Toyota"
  
}

### GET BRANDS

GET {{baseURL}}/brand

### GET MODELS

GET {{baseURL}}/vehicle-model

### Create a model
POST {{baseURL}}/vehicle-model
Content-Type: application/json

{
  "name": "Corolla",
  "brand": 1
}

### GET NOVELTYS 

GET {{baseURL}}/novelty

### Create a novelty 
POST {{baseURL}}/novelty
Content-Type: application/json

{
  "name": "Revision",
  "format": "Inspeccion de estado a las ________"
}
