//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "base")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::commission::Entity")]
    Commission,
    #[sea_orm(has_many = "super::correspondence::Entity")]
    Correspondence,
    #[sea_orm(has_many = "super::issuance::Entity")]
    Issuance,
    #[sea_orm(has_many = "super::official::Entity")]
    Official,
    #[sea_orm(has_many = "super::part::Entity")]
    Part,
    #[sea_orm(has_many = "super::persona_situation::Entity")]
    PersonaSituation,
    #[sea_orm(has_many = "super::plate::Entity")]
    Plate,
    #[sea_orm(has_many = "super::register::Entity")]
    Register,
    #[sea_orm(has_many = "super::seclusion::Entity")]
    Seclusion,
    #[sea_orm(has_many = "super::temporal_seclusion::Entity")]
    TemporalSeclusion,
    #[sea_orm(has_many = "super::transport::Entity")]
    Transport,
    #[sea_orm(has_many = "super::transport_issuance::Entity")]
    TransportIssuance,
    #[sea_orm(has_many = "super::weapon::Entity")]
    Weapon,
}

impl Related<super::commission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Commission.def()
    }
}

impl Related<super::correspondence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Correspondence.def()
    }
}

impl Related<super::issuance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issuance.def()
    }
}

impl Related<super::official::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Official.def()
    }
}

impl Related<super::part::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Part.def()
    }
}

impl Related<super::persona_situation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaSituation.def()
    }
}

impl Related<super::plate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plate.def()
    }
}

impl Related<super::register::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Register.def()
    }
}

impl Related<super::seclusion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seclusion.def()
    }
}

impl Related<super::temporal_seclusion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemporalSeclusion.def()
    }
}

impl Related<super::transport::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transport.def()
    }
}

impl Related<super::transport_issuance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransportIssuance.def()
    }
}

impl Related<super::weapon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Weapon.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
