//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "brand")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::transport::Entity")]
    Transport,
    #[sea_orm(has_many = "super::vehicle_model::Entity")]
    VehicleModel,
}

impl Related<super::transport::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transport.def()
    }
}

impl Related<super::vehicle_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VehicleModel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
