//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "charge")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::official::Entity")]
    Official,
    #[sea_orm(has_many = "super::persona_operational::Entity")]
    PersonaOperational,
    #[sea_orm(has_many = "super::persona_situation::Entity")]
    PersonaSituation,
}

impl Related<super::official::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Official.def()
    }
}

impl Related<super::persona_operational::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaOperational.def()
    }
}

impl Related<super::persona_situation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaSituation.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
