//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "commission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub brigade_id: i32,
    pub authorized_official_id: Option<i32>,
    pub entry_at: DateTimeWithTimeZone,
    pub exit_at: Option<DateTimeWithTimeZone>,
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub observations: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brigade::Entity",
        from = "Column::BrigadeId",
        to = "super::brigade::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Brigade,
    #[sea_orm(has_one = "super::commission_actual_exit::Entity")]
    CommissionActualExit,
    #[sea_orm(has_many = "super::commission_official::Entity")]
    CommissionOfficial,
    #[sea_orm(has_many = "super::commission_reason::Entity")]
    CommissionReason,
    #[sea_orm(has_many = "super::commission_transport::Entity")]
    CommissionTransport,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::AuthorizedOfficialId",
        to = "super::official::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official,
}

impl Related<super::brigade::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brigade.def()
    }
}

impl Related<super::commission_actual_exit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionActualExit.def()
    }
}

impl Related<super::commission_official::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionOfficial.def()
    }
}

impl Related<super::commission_reason::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionReason.def()
    }
}

impl Related<super::commission_transport::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionTransport.def()
    }
}

impl Related<super::official::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Official.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
