//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "commission_reason")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub commission_id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub zone: Option<String>,
    pub municipality_id: i32,
    pub parish_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::commission::Entity",
        from = "Column::CommissionId",
        to = "super::commission::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Commission,
    #[sea_orm(
        belongs_to = "super::municipality::Entity",
        from = "Column::MunicipalityId",
        to = "super::municipality::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Municipality,
    #[sea_orm(
        belongs_to = "super::parish::Entity",
        from = "Column::ParishId",
        to = "super::parish::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Parish,
}

impl Related<super::commission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Commission.def()
    }
}

impl Related<super::municipality::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Municipality.def()
    }
}

impl Related<super::parish::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Parish.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
