//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "commission_transport")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub commission_id: i32,
    pub transport_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::commission::Entity",
        from = "Column::CommissionId",
        to = "super::commission::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Commission,
    #[sea_orm(
        belongs_to = "super::transport::Entity",
        from = "Column::TransportId",
        to = "super::transport::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Transport,
}

impl Related<super::commission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Commission.def()
    }
}

impl Related<super::transport::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transport.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
