//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "correspondence_document")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub correspondence_id: i32,
    pub type_id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::correspondence::Entity",
        from = "Column::CorrespondenceId",
        to = "super::correspondence::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Correspondence,
    #[sea_orm(
        belongs_to = "super::document_type::Entity",
        from = "Column::TypeId",
        to = "super::document_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DocumentType,
}

impl Related<super::correspondence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Correspondence.def()
    }
}

impl Related<super::document_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DocumentType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
