//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "country_verification")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub persona_id: i32,
    pub condition_id: i32,
    pub reported: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::persona::Entity",
        from = "Column::PersonaId",
        to = "super::persona::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persona,
    #[sea_orm(
        belongs_to = "super::status_condition::Entity",
        from = "Column::PersonaId",
        to = "super::status_condition::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    StatusCondition,
}

impl Related<super::persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persona.def()
    }
}

impl Related<super::status_condition::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StatusCondition.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
