//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inclusion_audit_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub inclusion_record_id: i32,
    pub action: String,
    pub table_affected: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub old_values: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub new_values: Option<String>,
    pub user_id: i32,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
