//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use super::sea_orm_active_enums::InclusionTypeEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inclusion_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub record_id: i32,
    pub r#type: InclusionTypeEnum,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    pub date_time: DateTime,
    pub auth_persona_id: i32,
    pub evidences_file_path: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::arrests::Entity")]
    Arrests,
    #[sea_orm(has_many = "super::complainants::Entity")]
    Complainants,
    #[sea_orm(has_many = "super::confiscated_items::Entity")]
    ConfiscatedItems,
    #[sea_orm(has_many = "super::diligencies::Entity")]
    Diligencies,
    #[sea_orm(has_many = "super::flagrants::Entity")]
    Flagrants,
    #[sea_orm(has_many = "super::inclusion_records_accuseds::Entity")]
    InclusionRecordsAccuseds,
    #[sea_orm(has_many = "super::inclusion_records_personas::Entity")]
    InclusionRecordsPersonas,
    #[sea_orm(has_many = "super::init_orders::Entity")]
    InitOrders,
    #[sea_orm(has_many = "super::investigations::Entity")]
    Investigations,
    #[sea_orm(has_many = "super::involved_objects::Entity")]
    InvolvedObjects,
    #[sea_orm(has_many = "super::judicial_presentations::Entity")]
    JudicialPresentations,
    #[sea_orm(has_many = "super::technical_expertises::Entity")]
    TechnicalExpertises,
}

impl Related<super::arrests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Arrests.def()
    }
}

impl Related<super::complainants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Complainants.def()
    }
}

impl Related<super::confiscated_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConfiscatedItems.def()
    }
}

impl Related<super::diligencies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Diligencies.def()
    }
}

impl Related<super::flagrants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Flagrants.def()
    }
}

impl Related<super::inclusion_records_accuseds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InclusionRecordsAccuseds.def()
    }
}

impl Related<super::inclusion_records_personas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InclusionRecordsPersonas.def()
    }
}

impl Related<super::init_orders::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InitOrders.def()
    }
}

impl Related<super::investigations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Investigations.def()
    }
}

impl Related<super::involved_objects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvolvedObjects.def()
    }
}

impl Related<super::judicial_presentations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JudicialPresentations.def()
    }
}

impl Related<super::technical_expertises::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TechnicalExpertises.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
