//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "inclusion_records_personas")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub inclusion_record_id: i32,
    pub persona_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inclusion_records::Entity",
        from = "Column::InclusionRecordId",
        to = "super::inclusion_records::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    InclusionRecords,
}

impl Related<super::inclusion_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InclusionRecords.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
