//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "init_orders")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub annotated_id: i32,
    pub organism_id: i32,
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub instruction: String,
    pub inclusion_record_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::inclusion_records::Entity",
        from = "Column::InclusionRecordId",
        to = "super::inclusion_records::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    InclusionRecords,
    #[sea_orm(
        belongs_to = "super::organism::Entity",
        from = "Column::OrganismId",
        to = "super::organism::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organism,
}

impl Related<super::inclusion_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InclusionRecords.def()
    }
}

impl Related<super::organism::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organism.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
