//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "investigations_order")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub annotated_id: i32,
    pub organism_id: i32,
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub instruction: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
