//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "issuance_weapon")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub weapon_id: i32,
    pub issuance_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::issuance::Entity",
        from = "Column::IssuanceId",
        to = "super::issuance::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Issuance,
    #[sea_orm(
        belongs_to = "super::weapon::Entity",
        from = "Column::WeaponId",
        to = "super::weapon::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Weapon,
}

impl Related<super::issuance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issuance.def()
    }
}

impl Related<super::weapon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Weapon.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
