//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod brand;
pub mod brigade;
pub mod division;
pub mod municipality;
pub mod organism;
pub mod permission;
pub mod register;
pub mod role;
pub mod role_permission;
pub mod state;
pub mod user;
pub mod vehicle_model;
