//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod brigada;
pub mod division;
pub mod estado;
pub mod marca;
pub mod modelo;
pub mod municipio;
pub mod organismo;
pub mod permission;
pub mod register;
pub mod role;
pub mod role_permission;
pub mod user;
