//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod brand;
pub mod brigade;
pub mod charge;
pub mod commission;
pub mod commission_actual_exit;
pub mod commission_official;
pub mod commission_reason;
pub mod commission_seized_transport;
pub mod commission_transport;
pub mod division;
pub mod family_relationship;
pub mod hierarchy;
pub mod municipality;
pub mod official;
pub mod organism;
pub mod parish;
pub mod permission;
pub mod register;
pub mod role;
pub mod role_permission;
pub mod seclusion;
pub mod seclusion_statuses;
pub mod seclusion_visit;
pub mod state;
pub mod temporal_seclusion;
pub mod transport;
pub mod transport_statuses;
pub mod transport_type;
pub mod user;
pub mod vehicle_model;
