//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "municipality")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub state: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::commission_reason::Entity")]
    CommissionReason,
    #[sea_orm(
        belongs_to = "super::state::Entity",
        from = "Column::State",
        to = "super::state::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    State,
}

impl Related<super::commission_reason::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionReason.def()
    }
}

impl Related<super::state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::State.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
