//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "municipio")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub nombre: String,
    pub estado: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::estado::Entity",
        from = "Column::Estado",
        to = "super::estado::Column::Nombre",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Estado,
}

impl Related<super::estado::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Estado.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
