//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "official")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub ci: String,
    pub last_name: String,
    pub first_name: String,
    #[sea_orm(column_type = "Text")]
    pub phone: String,
    pub charge_id: i32,
    pub hierarchy_id: i32,
    pub brigade_id: i32,
    pub code: Option<i32>,
    pub base_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::base::Entity",
        from = "Column::BaseId",
        to = "super::base::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Base,
    #[sea_orm(
        belongs_to = "super::brigade::Entity",
        from = "Column::BrigadeId",
        to = "super::brigade::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Brigade,
    #[sea_orm(
        belongs_to = "super::charge::Entity",
        from = "Column::ChargeId",
        to = "super::charge::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Charge,
    #[sea_orm(has_many = "super::commission_official::Entity")]
    CommissionOfficial,
    #[sea_orm(
        belongs_to = "super::hierarchy::Entity",
        from = "Column::HierarchyId",
        to = "super::hierarchy::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hierarchy,
    #[sea_orm(has_many = "super::part_official::Entity")]
    PartOfficial,
}

impl Related<super::base::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Base.def()
    }
}

impl Related<super::brigade::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brigade.def()
    }
}

impl Related<super::charge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Charge.def()
    }
}

impl Related<super::commission_official::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionOfficial.def()
    }
}

impl Related<super::hierarchy::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hierarchy.def()
    }
}

impl Related<super::part_official::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartOfficial.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
