//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organism")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub phone: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::persona_operational::Entity")]
    PersonaOperational,
    #[sea_orm(has_many = "super::persona_situation::Entity")]
    PersonaSituation,
    #[sea_orm(has_many = "super::register::Entity")]
    Register,
}

impl Related<super::persona_operational::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaOperational.def()
    }
}

impl Related<super::persona_situation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaSituation.def()
    }
}

impl Related<super::register::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Register.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
