//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "part_official")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub official_id: i32,
    pub part_id: i32,
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialId",
        to = "super::official::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Official,
    #[sea_orm(
        belongs_to = "super::part::Entity",
        from = "Column::PartId",
        to = "super::part::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Part,
}

impl Related<super::official::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Official.def()
    }
}

impl Related<super::part::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Part.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
