//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "part_development")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub part_id: i32,
    pub data: Json,
    pub date: Date,
    pub type_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::novelty::Entity",
        from = "Column::TypeId",
        to = "super::novelty::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Novelty,
    #[sea_orm(
        belongs_to = "super::part::Entity",
        from = "Column::PartId",
        to = "super::part::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Part,
}

impl Related<super::novelty::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Novelty.def()
    }
}

impl Related<super::part::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Part.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
