//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "part")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: DateTime,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::part_development::Entity")]
    PartDevelopment,
    #[sea_orm(has_many = "super::part_official::Entity")]
    PartOfficial,
    #[sea_orm(has_many = "super::part_responsability::Entity")]
    PartResponsability,
}

impl Related<super::part_development::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartDevelopment.def()
    }
}

impl Related<super::part_official::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartOfficial.def()
    }
}

impl Related<super::part_responsability::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartResponsability.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
