//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "part_responsability")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub part_id: i32,
    pub official_service_ci: String,
    pub official_receive_ci: String,
    pub official_block_ci: String,
    pub official_writer_ci: String,
    pub official_deliver_ci: String,
    pub official_receive_custody_ci: String,
    pub official_hr_ci: String,
    pub official_supervisor_ci: String,
    pub official_director_ci: String,
    pub official_dae_ci: String,
    pub official_die_ci: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialBlockCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official11,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialDaeCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official10,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialDeliverCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official9,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialDieCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official8,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialDirectorCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official7,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialHrCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official6,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialReceiveCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official5,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialReceiveCustodyCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official4,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialServiceCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official3,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialSupervisorCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official2,
    #[sea_orm(
        belongs_to = "super::official::Entity",
        from = "Column::OfficialWriterCi",
        to = "super::official::Column::Ci",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Official1,
    #[sea_orm(
        belongs_to = "super::part::Entity",
        from = "Column::PartId",
        to = "super::part::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Part,
}

impl Related<super::part::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Part.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
