//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "persona")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ci: String,
    pub front_photo: Option<String>,
    pub back_photo: Option<String>,
    pub passport_number: Option<String>,
    pub passport_expiration: Option<String>,
    pub passport_years_valid: Option<i32>,
    pub name: String,
    pub last_name: String,
    pub birthdate: String,
    pub age: i32,
    pub birthplace: String,
    pub address: String,
    pub phone: String,
    pub coordinates: Option<String>,
    pub genre: String,
    pub status_civil: String,
    pub bank_account: String,
    pub homeland_ci: String,
    pub vehicle_license: String,
    pub others: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::country_verification::Entity")]
    CountryVerification,
    #[sea_orm(has_many = "super::persona_children::Entity")]
    PersonaChildren,
    #[sea_orm(has_many = "super::persona_conyuge::Entity")]
    PersonaConyuge,
    #[sea_orm(has_many = "super::persona_health::Entity")]
    PersonaHealth,
    #[sea_orm(has_many = "super::persona_operational::Entity")]
    PersonaOperational,
    #[sea_orm(has_many = "super::persona_record::Entity")]
    PersonaRecord,
    #[sea_orm(has_many = "super::persona_relative::Entity")]
    PersonaRelative,
    #[sea_orm(has_many = "super::persona_traits::Entity")]
    PersonaTraits,
    #[sea_orm(has_many = "super::persona_work_experience::Entity")]
    PersonaWorkExperience,
    #[sea_orm(has_one = "super::user::Entity")]
    User,
}

impl Related<super::country_verification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CountryVerification.def()
    }
}

impl Related<super::persona_children::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaChildren.def()
    }
}

impl Related<super::persona_conyuge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaConyuge.def()
    }
}

impl Related<super::persona_health::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaHealth.def()
    }
}

impl Related<super::persona_operational::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaOperational.def()
    }
}

impl Related<super::persona_record::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaRecord.def()
    }
}

impl Related<super::persona_relative::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaRelative.def()
    }
}

impl Related<super::persona_traits::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaTraits.def()
    }
}

impl Related<super::persona_work_experience::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaWorkExperience.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
