//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "persona_course")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub persona_id: i32,
    pub name: String,
    pub institution_id: i32,
    pub date: Date,
    pub document: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institution::Entity",
        from = "Column::InstitutionId",
        to = "super::institution::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Institution,
}

impl Related<super::institution::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institution.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
