//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "persona_education")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub persona_id: i32,
    pub grade: String,
    pub institution_id: i32,
    pub profession_id: i32,
    pub end_date: Date,
    pub photo: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::institution::Entity",
        from = "Column::InstitutionId",
        to = "super::institution::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Institution,
    #[sea_orm(
        belongs_to = "super::persona::Entity",
        from = "Column::PersonaId",
        to = "super::persona::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persona,
    #[sea_orm(
        belongs_to = "super::profession::Entity",
        from = "Column::ProfessionId",
        to = "super::profession::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Profession,
}

impl Related<super::institution::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Institution.def()
    }
}

impl Related<super::persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persona.def()
    }
}

impl Related<super::profession::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
