//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "persona_situation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub persona_id: i32,
    pub situation_type: String,
    pub entry_type: Option<String>,
    pub division_id: Option<i32>,
    pub state_id: Option<i32>,
    pub base_id: Option<i32>,
    pub hierarchy_id: Option<i32>,
    pub charge_id: Option<i32>,
    pub division_origin_id: Option<i32>,
    pub state_origin_id: Option<i32>,
    pub base_origin_id: Option<i32>,
    pub hierarchy_origin_id: Option<i32>,
    pub charge_origin_id: Option<i32>,
    pub organism_origin_id: Option<i32>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::base::Entity",
        from = "Column::BaseId",
        to = "super::base::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Base2,
    #[sea_orm(
        belongs_to = "super::base::Entity",
        from = "Column::BaseOriginId",
        to = "super::base::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Base1,
    #[sea_orm(
        belongs_to = "super::charge::Entity",
        from = "Column::ChargeId",
        to = "super::charge::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Charge2,
    #[sea_orm(
        belongs_to = "super::charge::Entity",
        from = "Column::ChargeOriginId",
        to = "super::charge::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Charge1,
    #[sea_orm(
        belongs_to = "super::division::Entity",
        from = "Column::DivisionId",
        to = "super::division::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Division2,
    #[sea_orm(
        belongs_to = "super::division::Entity",
        from = "Column::DivisionOriginId",
        to = "super::division::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Division1,
    #[sea_orm(
        belongs_to = "super::hierarchy::Entity",
        from = "Column::HierarchyId",
        to = "super::hierarchy::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hierarchy2,
    #[sea_orm(
        belongs_to = "super::hierarchy::Entity",
        from = "Column::HierarchyOriginId",
        to = "super::hierarchy::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hierarchy1,
    #[sea_orm(
        belongs_to = "super::organism::Entity",
        from = "Column::OrganismOriginId",
        to = "super::organism::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Organism,
    #[sea_orm(
        belongs_to = "super::persona::Entity",
        from = "Column::PersonaId",
        to = "super::persona::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persona,
    #[sea_orm(
        belongs_to = "super::state::Entity",
        from = "Column::StateId",
        to = "super::state::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    State2,
    #[sea_orm(
        belongs_to = "super::state::Entity",
        from = "Column::StateOriginId",
        to = "super::state::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    State1,
}

impl Related<super::organism::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organism.def()
    }
}

impl Related<super::persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persona.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
