//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "persona_traits")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub persona_id: i32,
    pub build: String,
    pub height: i32,
    pub skin_color: String,
    pub has_tattoos: Option<bool>,
    pub tattoos_photo: Option<String>,
    pub eyes_color: String,
    pub eyes_type: String,
    pub hair_color: String,
    pub hair_type: String,
    pub eyebrow_type: String,
    pub nose_type: String,
    pub face_type: String,
    pub lips_type: String,
    pub hands_type: String,
    pub others: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::persona::Entity",
        from = "Column::PersonaId",
        to = "super::persona::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persona,
}

impl Related<super::persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persona.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
