//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "persona_operational")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub persona_id: i32,
    pub organism_id: i32,
    pub charge_id: i32,
    pub start_at: Date,
    pub end_at: Date,
    pub time: i32,
    pub phone: String,
    pub file: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::charge::Entity",
        from = "Column::ChargeId",
        to = "super::charge::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Charge,
    #[sea_orm(
        belongs_to = "super::organism::Entity",
        from = "Column::OrganismId",
        to = "super::organism::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Organism,
    #[sea_orm(
        belongs_to = "super::persona::Entity",
        from = "Column::PersonaId",
        to = "super::persona::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persona,
}

impl Related<super::charge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Charge.def()
    }
}

impl Related<super::organism::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organism.def()
    }
}

impl Related<super::persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persona.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
