//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "persona_children")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub persona_id: i32,
    pub name: String,
    pub last_name: String,
    pub birth_date: Date,
    pub age: i32,
    pub grade: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
