//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "plate")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub division_id: i32,
    pub datetime: DateTime,
    pub base_id: i32,
    pub state_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::base::Entity",
        from = "Column::DivisionId",
        to = "super::base::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Base,
    #[sea_orm(
        belongs_to = "super::division::Entity",
        from = "Column::DivisionId",
        to = "super::division::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Division,
    #[sea_orm(has_many = "super::plate_persona::Entity")]
    PlatePersona,
    #[sea_orm(
        belongs_to = "super::state::Entity",
        from = "Column::DivisionId",
        to = "super::state::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    State,
}

impl Related<super::base::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Base.def()
    }
}

impl Related<super::division::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Division.def()
    }
}

impl Related<super::plate_persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlatePersona.def()
    }
}

impl Related<super::state::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::State.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
