//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "plate_persona")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub plate_id: i32,
    pub persona_id: i32,
    pub new_state_id: i32,
    pub old_state_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::persona::Entity",
        from = "Column::PersonaId",
        to = "super::persona::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Persona,
    #[sea_orm(
        belongs_to = "super::plate::Entity",
        from = "Column::PlateId",
        to = "super::plate::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Plate,
    #[sea_orm(
        belongs_to = "super::state::Entity",
        from = "Column::NewStateId",
        to = "super::state::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    State2,
    #[sea_orm(
        belongs_to = "super::state::Entity",
        from = "Column::OldStateId",
        to = "super::state::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    State1,
}

impl Related<super::persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persona.def()
    }
}

impl Related<super::plate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
