//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::brand::Entity as Brand;
pub use super::brigade::Entity as Brigade;
pub use super::division::Entity as Division;
pub use super::municipality::Entity as Municipality;
pub use super::organism::Entity as Organism;
pub use super::permission::Entity as Permission;
pub use super::register::Entity as Register;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::state::Entity as State;
pub use super::user::Entity as User;
pub use super::vehicle_model::Entity as VehicleModel;
