//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::brigada::Entity as Brigada;
pub use super::division::Entity as Division;
pub use super::estado::Entity as Estado;
pub use super::marca::Entity as Marca;
pub use super::modelo::Entity as Modelo;
pub use super::municipio::Entity as Municipio;
pub use super::organismo::Entity as Organismo;
pub use super::permission::Entity as Permission;
pub use super::register::Entity as Register;
pub use super::role::Entity as Role;
pub use super::role_permission::Entity as RolePermission;
pub use super::user::Entity as User;
