//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "register")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub photo: Option<String>,
    pub ci: String,
    pub last_name: String,
    pub first_name: String,
    pub organism: Option<i32>,
    pub division: Option<i32>,
    pub is_official: bool,
    pub entry_date: DateTime,
    pub exit_date: Option<DateTime>,
    pub visit_reason: String,
    pub observations: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::division::Entity",
        from = "Column::Division",
        to = "super::division::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Division,
    #[sea_orm(
        belongs_to = "super::organism::Entity",
        from = "Column::Organism",
        to = "super::organism::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Organism,
}

impl Related<super::division::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Division.def()
    }
}

impl Related<super::organism::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organism.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
