//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use chrono::DateTime as ChronoDateTime;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Deserializer, Serialize};

fn deserialize_datetime<'de, D>(deserializer: D) -> Result<DateTime, D::Error>
where
    D: Deserializer<'de>,
{
    let dt_str = String::deserialize(deserializer)?;
    let dt = ChronoDateTime::parse_from_rfc3339(&dt_str).map_err(serde::de::Error::custom)?;

    // Convert to sea_orm::DateTime
    Ok(dt.naive_utc())
}

fn deserialize_optional_datetime<'de, D>(deserializer: D) -> Result<Option<DateTime>, D::Error>
where
    D: Deserializer<'de>,
{
    let opt_str = Option::<String>::deserialize(deserializer)?;
    match opt_str {
        Some(dt_str) => {
            let dt =
                ChronoDateTime::parse_from_rfc3339(&dt_str).map_err(serde::de::Error::custom)?;
            Ok(Some(dt.naive_utc()))
        }
        None => Ok(None),
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "register")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub photo: Option<String>,
    pub ci: String,
    pub last_name: String,
    pub first_name: String,
    pub organism: Option<i32>,
    pub division: Option<i32>,
    pub is_official: bool,
    #[serde(deserialize_with = "deserialize_datetime")]
    pub entry_date: DateTime,
    #[serde(deserialize_with = "deserialize_optional_datetime")]
    pub exit_date: Option<DateTime>,
    pub visit_reason: String,
    pub observations: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::division::Entity",
        from = "Column::Division",
        to = "super::division::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Division,
    #[sea_orm(
        belongs_to = "super::organismo::Entity",
        from = "Column::Organism",
        to = "super::organismo::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Organismo,
}

impl Related<super::division::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Division.def()
    }
}

impl Related<super::organismo::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organismo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
