//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "inclusion_type_enum"
)]
pub enum InclusionTypeEnum {
    #[sea_orm(string_value = "flagrant")]
    Flagrant,
    #[sea_orm(string_value = "complaint")]
    Complaint,
    #[sea_orm(string_value = "init_order")]
    InitOrder,
    #[sea_orm(string_value = "investigation")]
    Investigation,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "type_enum")]
pub enum TypeEnum {
    #[sea_orm(string_value = "official")]
    Official,
    #[sea_orm(string_value = "civil")]
    Civil,
}
