//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "seclusion_visit")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub seclusion_id: i32,
    pub ci: String,
    pub last_name: String,
    pub first_name: String,
    pub relationship_id: i32,
    pub phone: String,
    pub address: String,
    pub reason: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::family_relationship::Entity",
        from = "Column::RelationshipId",
        to = "super::family_relationship::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    FamilyRelationship,
    #[sea_orm(
        belongs_to = "super::seclusion::Entity",
        from = "Column::SeclusionId",
        to = "super::seclusion::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Seclusion,
}

impl Related<super::family_relationship::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FamilyRelationship.def()
    }
}

impl Related<super::seclusion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seclusion.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
