//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "seclusion")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub photo: Option<String>,
    pub ci: String,
    pub birthdate: Date,
    pub age: i32,
    pub last_name: String,
    pub first_name: String,
    pub reason: String,
    pub exit_reason: Option<String>,
    pub physical_state: String,
    pub outfit: Option<String>,
    pub belongings: Option<String>,
    pub observations: Option<String>,
    pub exit_at: Option<DateTime>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::seclusion_visit::Entity")]
    SeclusionVisit,
}

impl Related<super::seclusion_visit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeclusionVisit.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
