//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "state")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::division::Entity")]
    Division,
    #[sea_orm(has_many = "super::municipality::Entity")]
    Municipality,
    #[sea_orm(has_many = "super::persona_situation::Entity")]
    PersonaSituation,
    #[sea_orm(has_many = "super::plate::Entity")]
    Plate,
}

impl Related<super::division::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Division.def()
    }
}

impl Related<super::municipality::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Municipality.def()
    }
}

impl Related<super::persona_situation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PersonaSituation.def()
    }
}

impl Related<super::plate::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
