//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "temporal_seclusion")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub base_id: i32,
    pub commission_id: i32,
    pub ci: String,
    pub last_name: String,
    pub first_name: String,
    pub status_id: Option<i32>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::base::Entity",
        from = "Column::BaseId",
        to = "super::base::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Base,
    #[sea_orm(
        belongs_to = "super::commission::Entity",
        from = "Column::CommissionId",
        to = "super::commission::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Commission,
    #[sea_orm(
        belongs_to = "super::seclusion_statuses::Entity",
        from = "Column::StatusId",
        to = "super::seclusion_statuses::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SeclusionStatuses,
}

impl Related<super::base::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Base.def()
    }
}

impl Related<super::commission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Commission.def()
    }
}

impl Related<super::seclusion_statuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeclusionStatuses.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
