//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transport")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub type_id: i32,
    pub details: String,
    pub brand_id: i32,
    pub model_id: i32,
    #[sea_orm(unique)]
    pub plate: String,
    pub unit: String,
    pub status_id: Option<i32>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brand::Entity",
        from = "Column::BrandId",
        to = "super::brand::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    Brand,
    #[sea_orm(has_many = "super::commission_transport::Entity")]
    CommissionTransport,
    #[sea_orm(
        belongs_to = "super::transport_statuses::Entity",
        from = "Column::StatusId",
        to = "super::transport_statuses::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    TransportStatuses,
    #[sea_orm(
        belongs_to = "super::transport_type::Entity",
        from = "Column::TypeId",
        to = "super::transport_type::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    TransportType,
    #[sea_orm(
        belongs_to = "super::vehicle_model::Entity",
        from = "Column::ModelId",
        to = "super::vehicle_model::Column::Id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    VehicleModel,
}

impl Related<super::brand::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brand.def()
    }
}

impl Related<super::commission_transport::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommissionTransport.def()
    }
}

impl Related<super::transport_statuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransportStatuses.def()
    }
}

impl Related<super::transport_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransportType.def()
    }
}

impl Related<super::vehicle_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VehicleModel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
