//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transport_issuance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub assigned_persona_id: i32,
    pub assigned_transport_id: i32,
    pub has_charger: bool,
    pub ammo_count: i32,
    pub date_time: DateTime,
    pub r#type: String,
    pub assignance_days: i32,
    pub auth_by_id: i32,
    pub base_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::base::Entity",
        from = "Column::BaseId",
        to = "super::base::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Base,
    #[sea_orm(
        belongs_to = "super::persona::Entity",
        from = "Column::AssignedPersonaId",
        to = "super::persona::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Persona,
    #[sea_orm(
        belongs_to = "super::transport::Entity",
        from = "Column::AssignedTransportId",
        to = "super::transport::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transport,
    #[sea_orm(has_one = "super::transport_issuance_return::Entity")]
    TransportIssuanceReturn,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::AuthById",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::base::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Base.def()
    }
}

impl Related<super::persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Persona.def()
    }
}

impl Related<super::transport::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transport.def()
    }
}

impl Related<super::transport_issuance_return::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransportIssuanceReturn.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
