//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "transport_issuance_return")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub issuance_id: i32,
    pub returned_at: DateTime,
    pub has_charger: bool,
    pub returned_ammo: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub observations: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::transport_issuance::Entity",
        from = "Column::IssuanceId",
        to = "super::transport_issuance::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TransportIssuance,
}

impl Related<super::transport_issuance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TransportIssuance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
