//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "vehicle_model")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub brand: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::brand::Entity",
        from = "Column::Brand",
        to = "super::brand::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Brand,
    #[sea_orm(has_many = "super::transport::Entity")]
    Transport,
}

impl Related<super::brand::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Brand.def()
    }
}

impl Related<super::transport::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transport.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
