//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "weapon")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub type_id: i32,
    pub model_id: i32,
    pub photo: Option<String>,
    #[sea_orm(unique)]
    pub serial: String,
    pub entry_at: DateTime,
    pub document_id: Option<String>,
    pub base_id: i32,
    pub calibre_id: i32,
    pub position_id: i32,
    pub manteinance_at: Option<DateTime>,
    pub has_charger: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub observations: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::base::Entity",
        from = "Column::BaseId",
        to = "super::base::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Base,
    #[sea_orm(
        belongs_to = "super::calibre::Entity",
        from = "Column::BaseId",
        to = "super::calibre::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Calibre,
    #[sea_orm(has_many = "super::issuance_weapon::Entity")]
    IssuanceWeapon,
    #[sea_orm(
        belongs_to = "super::position::Entity",
        from = "Column::PositionId",
        to = "super::position::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Position,
    #[sea_orm(
        belongs_to = "super::weapon_model::Entity",
        from = "Column::ModelId",
        to = "super::weapon_model::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WeaponModel,
    #[sea_orm(
        belongs_to = "super::weapon_type::Entity",
        from = "Column::TypeId",
        to = "super::weapon_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WeaponType,
}

impl Related<super::base::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Base.def()
    }
}

impl Related<super::calibre::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Calibre.def()
    }
}

impl Related<super::issuance_weapon::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IssuanceWeapon.def()
    }
}

impl Related<super::position::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Position.def()
    }
}

impl Related<super::weapon_model::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WeaponModel.def()
    }
}

impl Related<super::weapon_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WeaponType.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
